Mwpw 162452
adobecom/mas pull request #118
Opened 2024-12-17 14:32 UTC by 3ch023

Resolve https://jira.corp.adobe.com/browse/MWPW-162452

Fix OST opening without promo override value.
Remove Gallery from mas - we should use the Milo one.
move `mas-commerce-service` into a Studio.
add commerce env switch (needed to test promocode in action)

what's missing: open ost with stage commerce env, will add it later

Test URLs:
- Before: https://main--mas--adobecom.hlx.live/studio.html
- After: https://MWPW-162452--mas--adobecom.hlx.live/studio.html

2025-01-09 17:12 UTC, yesil approved these changes

2025-01-13 11:23 UTC, st-angelo-adobe commented on studio/src/store.js
> +    new URLSearchParams(window.location.hash.slice(1)),
Maybe we could have a hash util, so that anywhere we want a param we can just access it like a normal object. Not saying it's needed here, since I'll work on the hash manager task I can think of something.

2025-01-13 12:22 UTC, st-angelo-adobe requested changes

2025-01-13 12:22 UTC, st-angelo-adobe commented on studio/src/studio.js
> +import Events from './events.js';
This is unused

2025-01-16 13:02 UTC, 3ch023 commented on studio/src/studio.js
> +            ${this.commerceEnv?.value == 'stage'
>Also I think the commerceEnv store, and stores in general should have correct values, and be validated. Right now you're setting the value directly from the param, and that could be anything. I see prod is the default, so when setting the commerceEnv store value, you can just validate there. It's better to always trust the store imo.

good point, addressing

>And then you can just write <mas-commerce-service env=${this.commerceEnv.value}></mas-commerce-service>

Unfortunately in `mas-commerce-service` env attribute is not observable so its not enough to toggle its value. to trigger commerce env swithc i need to readd to dom the whole `mas-commerce-service`. but let me try to fix it up a bit

2025-01-16 13:05 UTC, 3ch023 commented on studio/src/studio.js
> +            ${this.commerceEnv?.value == 'stage'
to add a bit more explanation if i remove if condition and just pass by the attribute value like this
<mas-commerce-service env=${this.commerceEnv.value}></mas-commerce-service>

lit will not recreate mas-commerce-service element in dom, it will only update the attribute. and i need to trigger element recreation

2025-01-16 13:09 UTC, 3ch023 commented on studio/src/studio.js
> +import Events from './events.js';
addressed

2025-01-16 13:10 UTC, 3ch023 commented on studio/src/store.js
> +    new URLSearchParams(window.location.hash.slice(1)),
agreed :)
yeah it fealt not good to me as well when i was adding it

2025-01-16 14:26 UTC, st-angelo-adobe commented on studio/src/studio.js
> +            ${this.commerceEnv?.value == 'stage'
Ah, I see. That's ok then. 👍

2025-01-16 14:27 UTC, st-angelo-adobe approved these changes

2025-01-16 15:12 UTC, yesil approved these changes

2025-01-20 15:46 UTC, merged